"""
Django settings for selteq_task project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from dotenv import load_dotenv
from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production; provide a dev fallback for local runs.
SECRET_KEY = os.getenv('SECRET_KEY') or 'dev-secret-key-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
    'django_celery_beat',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'jobs',
    'drf_spectacular',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'selteq_task.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'selteq_task.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',  # Use the correct backend
#         'NAME': 'selteq_db',   # Your database name
#         'HOST': 'localhost',            # Use 'localhost' if SQL Server is running on your machine
#         'PORT': '',                     # Leave this blank for the default port (1433)
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',  # Specify the correct ODBC driver
#             'extra_params': 'TrustServerCertificate=yes;Integrated Security=SSPI;',  # Windows Authentication
#         },
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',  # Use the correct backend
#         'NAME': 'selteq_db',  # Your database name
#         'HOST': 'host.docker.internal',  # Use 'host.docker.internal' to connect to the host machine
#         'PORT': '1433',  # Default port for SQL Server
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',  # Specify the correct ODBC driver
#             'extra_params': 'TrustServerCertificate=yes;Integrated Security=SSPI;',  # Windows Authentication
#         },
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "AsyncTaskProcessor"),
        "USER": os.getenv("DB_USER", "Admin"),
        "PASSWORD": os.getenv("DB_PASSWORD", "TaskProcessor@123"),
        "HOST": os.getenv("DB_HOST", '127.0.0.1'),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Use drf-spectacular's OpenAPI schema generator.
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings: exposes OpenAPI schema and configures JWT auth in the docs
SPECTACULAR_SETTINGS = {
    'TITLE': 'AsyncTaskProcessor API',
    'DESCRIPTION': 'API documentation for AsyncTaskProcessor',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,
    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SECURITY': [{'bearerAuth': []}],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
}

REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")
# Use TLS (rediss://) for RedisLabs connections and keep SSL options.
# If running locally with plain Redis, set REDIS_PASSWORD to blank and
# use plain redis:// via environment.
CELERY_BROKER_URL = f"redis://default:{REDIS_PASSWORD}@redis-17876.crce206.ap-south-1-1.ec2.cloud.redislabs.com:17876/0"

# CELERY_BROKER_USE_SSL = {
#     "ssl_cert_reqs": None,
# }

CELERY_RESULT_BACKEND = f"redis://default:{REDIS_PASSWORD}@redis-17876.crce206.ap-south-1-1.ec2.cloud.redislabs.com:17876/0"


CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'


# CELERY_TIMEZONE = 'UTC'

# settings.py

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

  
}